### ISSUE TITLE
Graveyard concert_tutorial demo

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_tutorials#26]
I'm going to graveyard this demo. It's point was to show multiple services in parallel.

The turtle concert demo now does this with turtlesim + turtle_pond + teleop (soon).

@jihoonl, @hughie any problems with this?

**Comment by jihoonl** [comment]
We should concert_tutorial until the new demo get stable and ready to use. All the reference we have created are pointing to the concert_tutorial at the moment. So it is too dangerous to graveyard this now. I would create new demo for turtlesim + pond +teleop independent from concert_tutorial.

**Comment by hughie** [comment]
We made tutorial with concert_tutorial and shared information to project
member and internal user. So we need it yet. How about when new version
tutorial came out and replace it?

2014-02-12 11:07 GMT+09:00 Daniel Stonier notifications@github.com:

**Comment by stonier** [comment]
It's already out. There's just no reason to have concert_tutorial around anymore as the other tutorials already cover the parallel service feature.

I don't mind leaving it in for a little while though. One point that is worth remembering from this thread:

> Live documentation is **good**. Copies are **evil**.

While our software is changing while in development with partners, this is very, very important.
