### ISSUE TITLE
Spawning fails if turtlesim is renamed

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tutorials#31]

**Comment by stonier** [comment]
What does this mean?

**Comment by jihoonl** [comment]
I have renamed turtlesim name as `new_turtle_sim_name`  in solution configuration. And it didn't spawn turtles.

**Comment by stonier** [comment]
Got it. I'll look at it.

**Comment by stonier** [comment]
This is happening the turtle launcher:

```
    <node pkg="rocon_service_turtlesim" type="hatchling.py" name="$(anon hatchling)">
      <remap from="remote_controller" to="app_manager/remote_controller"/>
      <!-- Concert turtlesim service remaps --> 
      <remap from="spawn/request" to="services/turtlesim/spawn/request"/>
      <remap from="spawn/response" to="services/turtlesim/spawn/response"/>
      <remap from="kill/request" to="services/turtlesim/kill/request"/>
      <remap from="kill/response" to="services/turtlesim/kill/response"/>
    </node>
```

Remaps are hardcoded _spank_.

**Comment by stonier** [comment]
I can fix this by looking up `/concert/services/list`. However that is of no use to me right now - nothing in that list tells me that a service is a `rocon_service_turtlesim/turtlesim` service.

Looks like we need the resource name in the service specification like you were planning. It helps us see what 'types' of services are running.

**Comment by stonier** [comment]
This problem will be obsoleted by `turtle_herder` version 2 as the clients will no longer need to do a turtlesim lookup.

Since this is not urgent, closing for now. Reopen if it becomes urgent.
