### ISSUE TITLE
[chatter_concert] termination issues

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_tutorials#61]
Occasionally chatter concert has some failures when terminating. These are sometimes difficult to reproduce but need to be cleaned up. Chatter concert is the first thing a rocon concert user will see - it absolutely needs to work.

This issue is for listing up the problems.

**Comment by stonier** [comment]
A rocon_launch terminal id?:

```
Invalid pid value [None][an integer is required]
```

**Comment by stonier** [comment]
Clients sometimes hang saying they can't contact the hub (past exact output error when we see it here).

**Comment by stonier** [comment]
Moved discussion of termination issues to #61.

**Comment by stonier** [comment]
Closing this issue here - remaining problems moved out into other issues.

Guys - if you see problems with chatter concert, please make it a priority to document and chase these down. In the first 10-20 runs of it I was running into various problems (outside my newbie not having updated rocon_tools thing). If I'd have been a new user, I would have given up by now.

**Comment by jihoonl** [comment]
There is an issue open in rocon_tools regarding this. https://github.com/robotics-in-concert/rocon_tools/issues/53

**Comment by stonier** [comment]
Thanks for the redirect

**Comment by stonier** [comment]
No longer doing chatter concert as we were, should be much simpler now.
